# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c7056527126ece921e56374887987bff3cad614172c3150a7f952d07363894dfcf7e26acfb84508a6b3769c8cc9f8d5a2dbfd27c462dee83b5498fabad573d7

test:
  secret_key_base: 4feb0580f61a779410ad6a42efa7211ec71d2d3757ae5781f18151c92898e8f0c41834224eda15b8aaededfee73a5d68ce2ef81117870a2700773313ff3ff3a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
